import type { EventParameterValue, ExecuteResult, MigrationPlan, MigrationSelection, NativePluginResponse, Option, ResponseGuard, VoiceflowEnvelope, VoiceflowFailure, VoiceflowWarning, XYOpsJob, XYOpsJobResponse, XYOpsLaunchResponse, XYOpsResponse, XYOpsWaitJob, XYOpsWaitResponse } from "./types";

type IsRecord = (value: unknown) => value is Readonly<Record<string, unknown>>;
const isRecord: IsRecord = (value): value is Readonly<Record<string, unknown>> => typeof value === "object" && value !== null && !Array.isArray(value);
type IsNonEmptyString = (value: unknown) => value is string;
const isNonEmptyString: IsNonEmptyString = (value): value is string => typeof value === "string" && value.trim().length > 0;
type IsOption = (value: unknown) => value is Option;
export const isOption: IsOption = (value): value is Option => isRecord(value) && isNonEmptyString(value.value) && isNonEmptyString(value.label);
type IsOptionResult = (value: unknown) => value is Readonly<{ options: readonly Option[] }>;
export const isOptionResult: IsOptionResult = (value): value is Readonly<{ options: readonly Option[] }> => isRecord(value) && Array.isArray(value.options) && value.options.every(isOption);
// XYOpsResponse precedes the signature alias for its guard by design.
type IsXYOpsResponse = (value: unknown) => value is XYOpsResponse;
export const isXYOpsResponse: IsXYOpsResponse = (value): value is XYOpsResponse => isRecord(value) && (typeof value.code === "number" || typeof value.code === "string") && (!("description" in value) || typeof value.description === "string") && (!("id" in value) || typeof value.id === "string");
type IsNativePluginResponse = (value: unknown) => value is NativePluginResponse;
export const isNativePluginResponse: IsNativePluginResponse = (value): value is NativePluginResponse => isRecord(value) && value.xy === 1 && value.complete === true && (typeof value.code === "number" || typeof value.code === "string") && isRecord(value.data) && "voiceflow" in value.data;
type IsNativePluginData = (value: unknown) => value is Readonly<{ voiceflow: unknown }>;
const isNativePluginData: IsNativePluginData = (value): value is Readonly<{ voiceflow: unknown }> => isRecord(value) && "voiceflow" in value;
type NormalizeVoiceflowResponse = (value: unknown) => unknown;
export const normalizeVoiceflowResponse: NormalizeVoiceflowResponse = (value) => isNativePluginResponse(value) ? value.data.voiceflow : isNativePluginData(value) ? value.voiceflow : value;
type IsXYOpsLaunchResponse = (value: unknown) => value is XYOpsLaunchResponse;
export const isXYOpsLaunchResponse: IsXYOpsLaunchResponse = (value): value is XYOpsLaunchResponse => isXYOpsResponse(value) && isNonEmptyString(value.id);
type IsJobLaunch = (value: unknown) => value is Readonly<{ id: string }>;
export const isJobLaunch: IsJobLaunch = (value): value is Readonly<{ id: string }> => isRecord(value) && isNonEmptyString(value.id);
type IsXYOpsJob = (value: unknown) => value is XYOpsJob;
export const isXYOpsJob: IsXYOpsJob = (value): value is XYOpsJob => isRecord(value) && (!("completed" in value) || value.completed === null || typeof value.completed === "boolean" || typeof value.completed === "number") && (typeof value.code === "number" || typeof value.code === "string") && (!("description" in value) || typeof value.description === "string") && (!("output" in value) || value.output === null || typeof value.output === "string");
type IsXYOpsJobResponse = (value: unknown) => value is XYOpsJobResponse;
export const isXYOpsJobResponse: IsXYOpsJobResponse = (value): value is XYOpsJobResponse => isXYOpsResponse(value) && isRecord(value.job) && isNonEmptyString(value.job.id) && isXYOpsJob(value.job);
type IsXYOpsWaitJob = (value: unknown) => value is XYOpsWaitJob;
export const isXYOpsWaitJob: IsXYOpsWaitJob = (value): value is XYOpsWaitJob => isRecord(value) && isNonEmptyString(value.id) && (typeof value.code === "number" || typeof value.code === "string") && (!("description" in value) || typeof value.description === "string") && (!("output" in value) || value.output === null || typeof value.output === "string") && (!("completed" in value) || value.completed === null || typeof value.completed === "boolean" || typeof value.completed === "number");
type IsXYOpsWaitResponse = (value: unknown) => value is XYOpsWaitResponse;
export const isXYOpsWaitResponse: IsXYOpsWaitResponse = (value): value is XYOpsWaitResponse => isRecord(value) && (typeof value.code === "number" || typeof value.code === "string") && (!("description" in value) || typeof value.description === "string") && isXYOpsWaitJob(value.job);
type IsVoiceflowEnvelope = <T>(resultGuard: ResponseGuard<T>) => ResponseGuard<VoiceflowEnvelope<T>>;
export const isVoiceflowEnvelope: IsVoiceflowEnvelope = <T>(resultGuard: ResponseGuard<T>) => (value): value is VoiceflowEnvelope<T> => { if (!isRecord(value) || !isNonEmptyString(value.operation) || !isNonEmptyString(value.operationID)) return false; if (value.ok === true) return Array.isArray(value.warnings) && value.warnings.every(isWarning) && resultGuard(value.result); return value.ok === false && isFailure(value.error); };
type IsWarning = (value: unknown) => value is VoiceflowWarning;
const isWarning: IsWarning = (value): value is VoiceflowWarning => isRecord(value) && isNonEmptyString(value.code) && isNonEmptyString(value.message);
type IsFailure = (value: unknown) => value is VoiceflowFailure["error"];
const isFailure: IsFailure = (value): value is VoiceflowFailure["error"] => isRecord(value) && isNonEmptyString(value.code) && typeof value.message === "string" && typeof value.retryable === "boolean";
type IsCheckSessionResult = (value: unknown) => value is Readonly<{ active: boolean }>;
export const isCheckSessionResult: IsCheckSessionResult = (value): value is Readonly<{ active: boolean }> => isRecord(value) && typeof value.active === "boolean";
type IsMigrationSelection = (value: unknown) => value is MigrationSelection;
const isMigrationSelection: IsMigrationSelection = (value): value is MigrationSelection => isRecord(value) && ["sourceWorkspaceID", "sourceProjectID", "sourceVersionID", "destinationWorkspaceID", "destinationFolderID", "targetSchemaVersion"].every((key) => isNonEmptyString(value[key]));
type IsMigrationPlan = (value: unknown) => value is MigrationPlan;
export const isMigrationPlan: IsMigrationPlan = (value): value is MigrationPlan => { if (!isRecord(value) || !isNonEmptyString(value.planID) || !isMigrationSelection(value.selection)) return false; const labels = value.labels; return isRecord(labels) && ["sourceWorkspace", "sourceProject", "sourceVersion", "destinationWorkspace", "destinationFolder"].every((key) => isNonEmptyString(labels[key])); };
type IsExecuteResult = (value: unknown) => value is ExecuteResult;
export const isExecuteResult: IsExecuteResult = (value): value is ExecuteResult => { if (!isRecord(value) || !isNonEmptyString(value.planID) || !isMigrationSelection(value.selected)) return false; if (!["exportStatus", "exportBytes", "importStatus", "importBytes"].every((key) => typeof value[key] === "number")) return false; return typeof value.apiKeyRetrieved === "boolean" && isRecord(value.imported) && isNonEmptyString(value.imported.projectID); };
type IsEventParameterEntry = (entry: readonly [string, EventParameterValue | undefined]) => entry is [string, EventParameterValue];
export const isEventParameterEntry: IsEventParameterEntry = (entry): entry is [string, EventParameterValue] => typeof entry[1] === "string" || typeof entry[1] === "boolean";
type IsRetryableStatus = (status: number) => boolean;
export const isRetryableStatus: IsRetryableStatus = (status) => status === 408 || status === 429 || status >= 500;
type IsSuccessfulCode = (code: number | string) => boolean;
export const isSuccessfulCode: IsSuccessfulCode = (code) => code === 0 || code === 200 || code === "0" || code === "200" || code === "OK" || code === "ok";
type IsCompletedJob = (completed: boolean | number | null | undefined) => boolean;
export const isCompletedJob: IsCompletedJob = (completed) => completed === true || (typeof completed === "number" && completed > 0);
type IsInvalidDuration = (value: number) => boolean;
export const isInvalidDuration: IsInvalidDuration = (value) => [!Number.isFinite(value), value <= 0, value > 3_600_000].some(Boolean);
type IsHTTPURL = (url: URL) => boolean;
export const isHTTPURL: IsHTTPURL = (url) => url.protocol === "http:" || url.protocol === "https:";
